In [1]:
import pandas as pd

In [7]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [45]:
df = pd.read_excel("expenses_income_summary.csv.xlsx")

In [46]:
df.head(20)

,Date,title,category,account,amount,currency,type,transfer-amount,transfer-currency,to-account,receive-amount,receive-currency,description,due-date,id
0,2024-08-11 13:56:59.652,Karthik,Bills & Fees,Savings Bank,45.0,INR,EXPENSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74e78631-db14-4495-bfb9-85546b0bd2fe
1,2024-08-10 16:09:55.986,Juice,Food & Drinks,Cash,40.0,INR,EXPENSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65e12e62-9f63-4c6c-b452-6c7b42fbfb7f
2,2024-08-09 10:25:21.618,Tire,Transport,Cash,10.0,INR,EXPENSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9ecd93bd-a835-4263-86e2-99fea475fa37
3,2024-08-07 03:57:24.944,Baba,Bills & Fees,Savings Bank,200.0,INR,EXPENSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00d39b2c-e722-485a-85ca-28f6506dc674
4,2024-08-04 13:09:08.452,Reward,Bills & Fees,Salary Bank,4.0,INR,INCOME,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3861d205-3245-4926-ad69-4491b0bff547
5,2024-08-04 13:07:41.831,Baba,Bills & Fees,Savings Bank,500.0,INR,EXPENSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d56409a4-8deb-4a73-84e7-dfcc630b90dd
6,2024-08-02 15:25:39.300,Grocery,Bills & Fees,Salary Bank,30.0,INR,EXPENSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,063983ae-2b62-4ba6-b53f-405af48101c2
7,2024-08-02 05:25:11.454,Petrol,Transport,Savings Bank,100.0,INR,EXPENSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,593dec7f-97fe-4114-89ff-71c8c7591ef8
8,2024-08-02 03:58:59.121,Adjust balance,NaN,Cash,74.0,INR,EXPENSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71621720-2c82-4a49-8474-ba22cc9a3c99
9,2024-08-02 03:56:52.237,Adjust balance,NaN,Savings Bank,102.0,INR,EXPENSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9d36ebc2-45e0-4dc2-8bf5-ec9cdb05925c
10,2024-08-01 13:47:08.112,Haircut,Bills & Fees,Savings Bank,152.0,INR,EXPENSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dba89b5e-346d-439b-aa8b-19c42ea5a8ca
11,2024-08-01 13:46:53.758,Baba,Bills & Fees,Savings Bank,500.0,INR,EXPENSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3c916050-ffd6-45bd-a24c-6d5a9ffda846
12,2024-07-31 14:34:25.800,Print,Bills & Fees,Savings Bank,22.0,INR,EXPENSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a474cddc-bbe2-4cfc-8fa8-8aa013b0260a
13,2024-07-31 13:49:37.981,License,Bills & Fees,Savings Bank,300.0,INR,EXPENSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00ee0c6b-7b05-4daa-9a55-0aa7b444be17
14,2024-07-26 14:48:03.223,Noodles,Food & Drinks,Savings Bank,70.0,INR,EXPENSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,e58169a9-810b-4539-b94c-8d5f009697c2
15,2024-07-20 04:54:12.554,Adjust balance,NaN,Savings Bank,0.0,INR,INCOME,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5f6d8272-22b5-4e0f-9890-21458f421a85
16,2024-07-20 04:53:54.600,Breakfast,Food & Drinks,Cash,30.0,INR,EXPENSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81a3f436-7623-419e-8e87-2cbdd29a0476
17,2024-07-20 04:53:37.992,Maa,Bills & Fees,Cash,50.0,INR,EXPENSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eff51027-fd36-4e8b-858c-70bc173f17c2
18,2024-07-15 16:02:44.240,Adjust balance,NaN,Cash,3.0,INR,EXPENSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bd394f07-67b4-44ec-8071-e7fbcf43c84d
19,2024-07-15 08:50:27.789,Rent,Bills & Fees,Savings Bank,3800.0,INR,EXPENSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94568f6d-f1d2-43bb-bf34-d93c7f124262

In [22]:
df.shape

(1155, 15)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1155 entries, 0 to 1154
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               1155 non-null   datetime64[ns]
 1   title              1131 non-null   object
 2   category           994 non-null    object
 3   account            1155 non-null   object
 4   amount             1155 non-null   float64
 5   currency           1155 non-null   object
 6   type               1155 non-null   object
 7   transfer-amount    44 non-null     float64
 8   transfer-currency  44 non-null     object
 9   to-account         44 non-null     object
 10  receive-amount     44 non-null     float64
 11  receive-currency   44 non-null     object
 12  description        1 non-null      float64
 13  due-date           0 non-null      float64
 14  id                 1155 non-null   object
dtypes: datetime64[ns](1), float64(5), object(9)
memory usage: 135.5+ KB

In [47]:
# 2. FIX ZERO AMOUNT ISSUE
# Replace amount=0 with transfer-amount
df['amount'] = df.apply(
    lambda row: row['transfer-amount'] if row['amount'] == 0 else row['amount'],
    axis=1
)

In [54]:
df.head(64)

,date,amount,category,account,title,type
0,2024-08-11 13:56:59.652,45.0,Bills & Fees,Savings Bank,Karthik,EXPENSE
1,2024-08-10 16:09:55.986,40.0,Food & Drinks,Cash,Juice,EXPENSE
2,2024-08-09 10:25:21.618,10.0,Transport,Cash,Tire,EXPENSE
3,2024-08-07 03:57:24.944,200.0,Bills & Fees,Savings Bank,Baba,EXPENSE
4,2024-08-04 13:09:08.452,4.0,Bills & Fees,Salary Bank,Reward,INCOME
...,...,...,...,...,...,...
59,2024-06-27 14:35:22.527,20.0,Transport,Cash,Bus,EXPENSE
60,2024-06-27 14:33:37.949,10.0,Transport,Salary Bank,Metro,EXPENSE
61,2024-06-27 13:24:27.059,200.0,Bills & Fees,Cash,Grocery,EXPENSE
62,2024-06-27 02:20:46.881,2500.0,Bills & Fees,Salary Bank,Withdraw,TRANSFER
63,2024-06-26 16:20:10.049,200.0,Transport,Salary Bank,Cab,EXPENSE

In [49]:
# 3. SELECT REQUIRED COLUMNS
df.columns = df.columns.str.strip().str.lower()
df = df[['date', 'amount', 'category','account', 'title', 'type']]

In [50]:
print(df['account'].unique())

['Savings Bank' 'Cash' 'Salary Bank' 'Metro Card']

In [51]:
df.head()

,date,amount,category,account,title,type
0,2024-08-11 13:56:59.652,45.0,Bills & Fees,Savings Bank,Karthik,EXPENSE
1,2024-08-10 16:09:55.986,40.0,Food & Drinks,Cash,Juice,EXPENSE
2,2024-08-09 10:25:21.618,10.0,Transport,Cash,Tire,EXPENSE
3,2024-08-07 03:57:24.944,200.0,Bills & Fees,Savings Bank,Baba,EXPENSE
4,2024-08-04 13:09:08.452,4.0,Bills & Fees,Salary Bank,Reward,INCOME

In [59]:
df.isnull().sum()

date        0
amount      0
category    0
account     0
title       0
type        0
dtype: int64

In [58]:
# fill amount nulls with 0
df['amount'] = df['amount'].fillna(0)

C:\Users\maryam\AppData\Local\Temp\ipykernel_2008\2645417980.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['amount'] = df['amount'].fillna(0)

In [55]:
# fill category nulls
df['category'] = df['category'].fillna("not defined")

C:\Users\maryam\AppData\Local\Temp\ipykernel_2008\3482786954.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['category'] = df['category'].fillna("not defined")

In [57]:
# fill title nulls using account
df['title'] = df['title'].fillna(df['account'])

C:\Users\maryam\AppData\Local\Temp\ipykernel_2008\1228242441.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['title'] = df['title'].fillna(df['account'])

In [60]:
# 5. DATE CONVERSION
df['date'] = pd.to_datetime(df['date'])

C:\Users\maryam\AppData\Local\Temp\ipykernel_2008\1339635089.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['date'] = pd.to_datetime(df['date'])

In [62]:
# 6. CLEAN TEXT DATA

df['title'] = df['title'].str.lower()
df['category'] = df['category'].str.lower()

df['title'] = df['title'].str.replace(r'[^a-zA-Z0-9 ]', '', regex=True)

df['title'] = df['title'].str.strip()
df['category'] = df['category'].str.strip()

C:\Users\maryam\AppData\Local\Temp\ipykernel_2008\3320464390.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['title'] = df['title'].str.lower()
C:\Users\maryam\AppData\Local\Temp\ipykernel_2008\3320464390.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['category'] = df['category'].str.lower()
C:\Users\maryam\AppData\Local\Temp\ipykernel_2008\3320464390.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['title'] = df['title'].str.replace(r'[^a-zA-Z0-9 ]', '', regex=True)
C:\Users\maryam\AppData\Local\Temp\ipykernel_2008\3320464390.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['title'] = df['title'].str.strip()
C:\Users\maryam\AppData\Local\Temp\ipykernel_2008\3320464390.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['category'] = df['category'].str.strip()

In [63]:
df.head(5)

,date,amount,category,account,title,type
0,2024-08-11 13:56:59.652,45.0,bills & fees,Savings Bank,karthik,EXPENSE
1,2024-08-10 16:09:55.986,40.0,food & drinks,Cash,juice,EXPENSE
2,2024-08-09 10:25:21.618,10.0,transport,Cash,tire,EXPENSE
3,2024-08-07 03:57:24.944,200.0,bills & fees,Savings Bank,baba,EXPENSE
4,2024-08-04 13:09:08.452,4.0,bills & fees,Salary Bank,reward,INCOME

In [65]:
# 7. FILTER ONLY EXPENSES
df = df[df['type'].str.lower() == 'expense']
# 8. REMOVE INVALID AMOUNTS
df = df[df['amount'] > 0]

In [68]:
# =========================
# 9. FEATURE ENGINEERING
# =========================
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['weekday'] = df['date'].dt.weekday

In [69]:
df.head(5)

,date,amount,category,account,title,type,month,day,weekday
0,2024-08-11 13:56:59.652,45.0,bills & fees,Savings Bank,karthik,EXPENSE,8,11,6
1,2024-08-10 16:09:55.986,40.0,food & drinks,Cash,juice,EXPENSE,8,10,5
2,2024-08-09 10:25:21.618,10.0,transport,Cash,tire,EXPENSE,8,9,4
3,2024-08-07 03:57:24.944,200.0,bills & fees,Savings Bank,baba,EXPENSE,8,7,2
5,2024-08-04 13:07:41.831,500.0,bills & fees,Savings Bank,baba,EXPENSE,8,4,6

In [70]:
# =========================
# 10. RESET INDEX
# =========================
df = df.reset_index(drop=True)

In [71]:
# =========================
# 11. SAVE CLEAN DATA
# =========================
df.to_csv("cleaned_expenses.csv", index=False)